# Generated by Django 4.1.7 on 2023-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=12)),
            ],
        ),
    ]
